baseURL = "https://marcopizzolato.com/"
languageCode = "en-us"
title = "Marco Pizzolato Portfolio"
theme = "mediumish-gohugo-theme"
summaryLength = 25
DefaultContentLanguage = "en"
copyright = "Marco Pizzolato - All rights reserved"
enableEmoji = true
publishDir = "public" # directory where I publish my website 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-132680808-1"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
  logo = "/images/Portfolio-02.png"
  logo2 = "/images/BlackGlobe.png"
  description ="This is the porfolio of Marco Pizzolato" #description of the website for the search engines
  #mailchimp = "you can provide a mailchimp-link here"


[params.author] # not sure where these go
  name = "Marco Pizzolato"
  thumbnail = "/images/marco_rea2.jpg"
  description = "Creator of this blog."


[params.index]
  picture = "./images/marcopizzo.jpg"
  title = "Marco Pizzolato"
  subtitle = "GIS Expert & Environmental Scientist"
  mdtext = '''
\
GIS Expert with a comprehensive background in environmental science; and three years experience in humanitarian response in East Africa, managing assessments, completing data analysis and producing vital information products to inform all NGOs active in the region.

Eager to continue on a steep learning curve and deepen my technical ability, I recently completed a MSc Geographical Information Sciences (GIS) at the University of Edinburgh, one of the world leading institutions for higher education.
The combination of GIS, data analysis, <i>and data visualization<i> allows me to explore the data, uncover patterns and relationships, and convey information to a wide audience; going beyond traditional statistical methods.

My passion lies in tying together GIS with my background in environmental science and working with NGOs, to the field of data analysis, environmental monitoring and protection.
\
\
'''
  alertbar = false

[params.social]
  github = "Marcopizzo87"
  linkedin = "pizzolatomarco"
  pdf = "file/d/16nn7L30nMfCIKSLkRq1Sbh7QR76H-Frk/view?usp=sharing"
  mail = "contact@marcopizzolato.com"
  # xing = "<username>"
  # medium = "<username>"

## Main Menu
[[menu.main]]
    name = "Works"
    identifier = "Works"
    weight = 1
    url = "/"
   
   
#[[menu.main]]
#    name = "Works"
#    weight = 2
#    identifier = "works"
#    url = "/static/imprint"
  
[[menu.main]]
    name = "Curriculum"
    identifier = "cv"
    weight = 2
    url = "/static/vitae"

[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 3
    url = "/bio/bio"