baseURL = "https://marcopizzolato.com/"
languageCode = "en-us"
title = "Marco Pizzolato Portfolio"
theme = "mediumish-gohugo-theme"
summaryLength = 25
DefaultContentLanguage = "en"
copyright = "Marco Pizzolato - All rights reserved"
enableEmoji = true
publishDir = "public" # directory where I publish my website 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-132680808-1"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
  logo = "/images/Portfolio-02.png"
  logo2 = "/images/BlackGlobe.png"
  description ="This is the porfolio of Marco Pizzolato" #description of the website for the search engines
  #mailchimp = "you can provide a mailchimp-link here"


[params.author] # not sure where these go
  name = "Marco Pizzolato"
  thumbnail = "/images/marco_rea2.jpg"
  description = "Creator of this blog."


[params.index]
  picture = "./images/marcopizzo.jpg"
  title = "Marco Pizzolato"
  subtitle = "GIS Expert & Environmental Scientist"
  mdtext = '''
\
Welcome to my personal website! 
This space is a collection of some of the works I have completed so far, from my time in South Sudan responding to the on-going crisis, to my Master in GIS at Edinburgh and other data explorations mainly with R. 

A little about me...
Dynamic and energetic I am very passionate about the projects I get involved in. I am always looking for new projects to embark on which will challenge my brain bringing out my inventiveness, creativity and imagination to find the best solution. 
Strongly believing that <i>“Together we stand, alone we fall”</i> I always collaborate in a profitable way with my team members, often building over time strong friendships.

Happy exploring and get in touch if you want to know more! 
\
\
'''
  alertbar = false

[params.social]
  github = "Marcopizzo87"
  linkedin = "pizzolatomarco"
  pdf = "file/d/16nn7L30nMfCIKSLkRq1Sbh7QR76H-Frk/view?usp=sharing"
  mail = "contact@marcopizzolato.com"
  # xing = "<username>"
  # medium = "<username>"

## Main Menu
[[menu.main]]
    name = "Works"
    identifier = "Works"
    weight = 1
    url = "/"
   
   
#[[menu.main]]
#    name = "Works"
#    weight = 2
#    identifier = "works"
#    url = "/static/imprint"
  
[[menu.main]]
    name = "Curriculum"
    identifier = "cv"
    weight = 2
    url = "/static/vitae"

[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 3
    url = "/bio/bio"